# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: petadoption.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'petadoption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11petadoption.proto\"G\n\x0bPetRequests\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\t\x12\r\n\x05\x62reed\x18\x04 \x01(\t\"-\n\x0fPetListResponse\x12\x1a\n\x04pets\x18\x01 \x03(\x0b\x32\x0c.PetRequests\",\n\rSearchRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"\"\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2l\n\x0bPetAdoption\x12.\n\x0bRegisterPet\x12\x0c.PetRequests\x1a\x11.RegisterResponse\x12-\n\tSearchPet\x12\x0e.SearchRequest\x1a\x10.PetListResponseB6\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'petadoption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_PETREQUESTS']._serialized_start=21
  _globals['_PETREQUESTS']._serialized_end=92
  _globals['_PETLISTRESPONSE']._serialized_start=94
  _globals['_PETLISTRESPONSE']._serialized_end=139
  _globals['_SEARCHREQUEST']._serialized_start=141
  _globals['_SEARCHREQUEST']._serialized_end=185
  _globals['_REGISTERRESPONSE']._serialized_start=187
  _globals['_REGISTERRESPONSE']._serialized_end=221
  _globals['_PETADOPTION']._serialized_start=223
  _globals['_PETADOPTION']._serialized_end=331
# @@protoc_insertion_point(module_scope)
